package com.educational.platform.java;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.lang.reflect.Constructor;
import java.lang.reflect.RecordComponent;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * Validates the behavioral contract of Java records used as integration events
 * and commands on Java 26: {@code equals()}, {@code hashCode()}, and
 * {@code toString()} auto-generated by the compiler.
 * <p>
 * {@link IntegrationEventContractJava26Test} verifies record structure
 * (components, accessors, naming). This test verifies the <em>behavioral</em>
 * contract: two records with identical component values must be equal, produce
 * the same hash code, and generate a meaningful toString. Spring's
 * {@code ApplicationEventPublisher} and logging infrastructure rely on these
 * contracts for event deduplication and diagnostics.
 */
public class Java26RecordEqualsHashCodeTest {

    // --- Integration event records: equals/hashCode contract ---

    static Stream<Arguments> integrationEventClasses() {
        return Stream.of(
                Arguments.of("com.educational.platform.courses.integration.event.SendCourseToApproveIntegrationEvent"),
                Arguments.of("com.educational.platform.administration.integration.event.CourseApprovedByAdminIntegrationEvent"),
                Arguments.of("com.educational.platform.administration.integration.event.CourseDeclinedByAdminIntegrationEvent"),
                Arguments.of("com.educational.platform.course.enrollments.integration.event.StudentEnrolledToCourseIntegrationEvent"),
                Arguments.of("com.educational.platform.course.reviews.integration.event.CourseRatingRecalculatedIntegrationEvent"),
                Arguments.of("com.educational.platform.users.integration.event.UserCreatedIntegrationEvent")
        );
    }

    @ParameterizedTest(name = "Record equals/hashCode contract should hold: {0}")
    @MethodSource("integrationEventClasses")
    void record_equalsHashCode_shouldBeConsistent(String className) throws Exception {
        Class<?> clazz = Class.forName(className);
        assertThat(clazz.isRecord()).as("%s must be a record", className).isTrue();

        RecordComponent[] components = clazz.getRecordComponents();
        Object[] args = buildDefaultArgs(components);

        Constructor<?> canonicalCtor = clazz.getDeclaredConstructor(
                Arrays.stream(components).map(RecordComponent::getType).toArray(Class[]::new)
        );
        canonicalCtor.setAccessible(true);

        Object instance1 = canonicalCtor.newInstance(args);
        Object instance2 = canonicalCtor.newInstance(args);

        assertThat(instance1)
                .as("Two records with identical components should be equal")
                .isEqualTo(instance2);

        assertThat(instance1.hashCode())
                .as("Equal records must produce the same hashCode")
                .isEqualTo(instance2.hashCode());
    }

    @ParameterizedTest(name = "Record toString should be non-empty: {0}")
    @MethodSource("integrationEventClasses")
    void record_toString_shouldBeNonEmpty(String className) throws Exception {
        Class<?> clazz = Class.forName(className);
        RecordComponent[] components = clazz.getRecordComponents();
        Object[] args = buildDefaultArgs(components);

        Constructor<?> canonicalCtor = clazz.getDeclaredConstructor(
                Arrays.stream(components).map(RecordComponent::getType).toArray(Class[]::new)
        );
        canonicalCtor.setAccessible(true);

        Object instance = canonicalCtor.newInstance(args);
        String toString = instance.toString();

        assertThat(toString)
                .as("Record toString should include class simple name")
                .contains(clazz.getSimpleName());
    }

    @ParameterizedTest(name = "Records with different values should not be equal: {0}")
    @MethodSource("integrationEventClasses")
    void record_withDifferentValues_shouldNotBeEqual(String className) throws Exception {
        Class<?> clazz = Class.forName(className);
        RecordComponent[] components = clazz.getRecordComponents();

        Constructor<?> canonicalCtor = clazz.getDeclaredConstructor(
                Arrays.stream(components).map(RecordComponent::getType).toArray(Class[]::new)
        );
        canonicalCtor.setAccessible(true);

        Object[] args1 = buildDefaultArgs(components);
        Object[] args2 = buildAlternateArgs(components);

        Object instance1 = canonicalCtor.newInstance(args1);
        Object instance2 = canonicalCtor.newInstance(args2);

        assertThat(instance1)
                .as("Records with different component values should not be equal")
                .isNotEqualTo(instance2);
    }

    // --- Records should work correctly in hash-based collections ---

    @ParameterizedTest(name = "Record instances should work in HashSet: {0}")
    @MethodSource("integrationEventClasses")
    void record_shouldWorkIn_hashBasedCollections(String className) throws Exception {
        Class<?> clazz = Class.forName(className);
        RecordComponent[] components = clazz.getRecordComponents();

        Constructor<?> canonicalCtor = clazz.getDeclaredConstructor(
                Arrays.stream(components).map(RecordComponent::getType).toArray(Class[]::new)
        );
        canonicalCtor.setAccessible(true);

        Object[] args = buildDefaultArgs(components);
        Object instance1 = canonicalCtor.newInstance(args);
        Object instance2 = canonicalCtor.newInstance(args);

        Set<Object> set = new HashSet<>();
        set.add(instance1);
        set.add(instance2);

        assertThat(set)
                .as("HashSet should deduplicate equal records")
                .hasSize(1);
    }

    // --- Record should not equal null or different type ---

    @Test
    void record_shouldNotEqual_null() {
        record TestEvent(UUID id) {}
        var event = new TestEvent(UUID.randomUUID());

        assertThat(event).isNotEqualTo(null);
    }

    @Test
    void record_shouldNotEqual_differentType() {
        record EventA(UUID id) {}
        record EventB(UUID id) {}
        UUID same = UUID.randomUUID();

        assertThat(new EventA(same)).isNotEqualTo(new EventB(same));
    }

    @Test
    void record_reflexiveEquals_shouldHold() {
        record TestEvent(UUID id, String name) {}
        var event = new TestEvent(UUID.randomUUID(), "test");

        assertThat(event).isEqualTo(event);
    }

    // --- Helpers ---

    private Object[] buildDefaultArgs(RecordComponent[] components) {
        return Arrays.stream(components)
                .map(c -> defaultValueFor(c.getType()))
                .toArray();
    }

    private Object[] buildAlternateArgs(RecordComponent[] components) {
        return Arrays.stream(components)
                .map(c -> alternateValueFor(c.getType()))
                .toArray();
    }

    private Object defaultValueFor(Class<?> type) {
        if (type == UUID.class) return UUID.fromString("00000000-0000-0000-0000-000000000001");
        if (type == String.class) return "default";
        if (type == int.class || type == Integer.class) return 1;
        if (type == long.class || type == Long.class) return 1L;
        if (type == double.class || type == Double.class) return 1.0;
        if (type == boolean.class || type == Boolean.class) return true;
        return null;
    }

    private Object alternateValueFor(Class<?> type) {
        if (type == UUID.class) return UUID.fromString("00000000-0000-0000-0000-000000000002");
        if (type == String.class) return "alternate";
        if (type == int.class || type == Integer.class) return 2;
        if (type == long.class || type == Long.class) return 2L;
        if (type == double.class || type == Double.class) return 2.0;
        if (type == boolean.class || type == Boolean.class) return false;
        return null;
    }
}
